version: "3"
services:
  grafana:
    container_name: grafana7_5_17
    image: orascope_grafana:7.5.17
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/custom:/usr/share/grafana/public/custom
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SERVER_HTTP_PORT=3000
    network_mode: "host"
